### ISSUE TITLE
"your device does not match the hardware requirements of this application"

### ISSUE THREAD

**Issue by GSSBMW** [ARM-software/perfdoc#2]
I build perfdoc sucessfully, and get file libVkLayer_mali_perf_doc.so . Besides the code of perfdoc, I clone data of KhronosGroup/SPIRV-Cross (https://github.com/KhronosGroup/SPIRV-Cross) to perfdoc-master/layer/SPIRV-Cross.

Machine: Huawei Mate 10, Xiaomi6
OS: Android 8.0
APP: build from a free Unity AssetStore project, https://www.assetstore.unity3d.com/cn/#!/content/52977
export ANDROID_ABI=arm64-v8a # Kirin970 of Mate10 uses Cortex-A73

When open the app, it prompt "your device does not match the hardware requirements of this application". After touch "continue", it just show me a full screen picture with purple color. (See the attached pictures). No error message being showed in logcat.

Any body use this vulkan layer successfully?

![screenshot_2018-01-18-14-46-56-332_com unity3d nature3d](https://user-images.githubusercontent.com/6941589/35084426-e1a6ece6-fc5e-11e7-9cc5-6d3aca077ade.png)
![image](https://user-images.githubusercontent.com/6941589/35084384-a8205552-fc5e-11e7-985e-1246c88a02e8.png)

**Comment by GSSBMW** [comment]
I have find the reason. From the logcat, I get this log:
01-18 19:01:52.504 14570 14590 W vulkan  : failed to open layer directory '/data/local/debug/vulkan': Permission denied

I don’t know why. I am root user, and the priviledge of /data/local/debug/vulkan is drwxrwxrwx。

So, I put libVkLayer_mali_perf_doc.so into /data/data/app-path/lib. Then it works.

**Comment by HansKristian-ARM** [comment]
This was resolved a while ago off-line, closing.

**Comment by Spectural** [comment]
Please Share how you solved this, i'm having the same problem and urgently trying to fix

**Comment by Spectural** [comment]
I'm new to this. where could i learn more on the topic of abi libraries? I'm using unity 2018.1

**Comment by HansKristian-ARM** [comment]
Unity is almost certainly going to be using armeabi-v7a. If you have a CLI handy, try `unzip -l your.apk`. For my particular APK (not Unity), I have:
```
  8239872  1980-00-00 00:00   lib/arm64-v8a/libnative.so
```
Which is a arm64-v8a ABI library, YMMV.

**Comment by Spectural** [comment]
OOOOHHHHH Okay that makes more sense. Thanks for the help Hanskristian.

**Comment by oscar-arturo** [comment]
I resolved :  https://docs.unity3d.com/Manual/GraphicsAPIs.html

**Comment by isnizal** [comment]
this helpful a lot. Thanks

**Comment by Najam-Kazmi** [comment]
> Make sure you are using the right ABI for the library. It needs to match your other native libraries (armeabi-v7a, vs arm64-v8a).

I am using Gameloop for CODM and still facing this issue. Can you help?
